sudo: required

services:
- docker

arch:
        packages:
        - archiso
        script:
        - "sudo ./build.sh -v"

script:
- "curl -s https://raw.githubusercontent.com/Catergos/arch-travis/master/arch-travis.sh | sudo bash"

