sudo: required

arch:
  repos:
    - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    # pacman packages
    - yaourt
    - archiso
  script:
    - sudo ./build.sh -v

script:
  - "travis_wait 30 sleep 1800 &"
  - curl -s https://raw.githubusercontent.com/xeon-zolt/arch-travis/master/arch-travis.sh | bash
